# Generated by Django 2.2.13 on 2024-04-07 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='nuban',
            new_name='ifsc',
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(default='emp210', max_length=70),
        ),
    ]
