# Generated by Django 2.2.13 on 2024-04-04 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0002_auto_20240404_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(default='emp689', max_length=70),
        ),
        migrations.AlterField(
            model_name='trainingprogram',
            name='employees',
            field=models.ManyToManyField(blank=True, null=True, to='hrms.Employee'),
        ),
    ]
