# Generated by Django 2.2.13 on 2024-04-04 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0003_auto_20240405_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(default='emp617', max_length=70),
        ),
        migrations.AlterField(
            model_name='trainingprogram',
            name='employees',
            field=models.ManyToManyField(blank=True, to='hrms.Employee'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('staff', 'status', 'date')},
        ),
    ]
