# Generated by Django 2.2.13 on 2024-04-07 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0003_auto_20240407_1604'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='history',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(default='emp564', max_length=70),
        ),
    ]
