# Generated by Django 2.2.13 on 2024-04-04 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0004_auto_20240405_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(default='emp167', max_length=70),
        ),
    ]
