# Generated by Django 2.2.13 on 2024-04-05 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0005_auto_20240405_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(default='emp535', max_length=70),
        ),
    ]
