# Generated by Django 2.2.13 on 2024-04-05 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0006_auto_20240405_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(default='emp242', max_length=70),
        ),
    ]
