# Generated by Django 2.2.13 on 2024-04-05 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0007_auto_20240405_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitment',
            name='role',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(default='emp358', max_length=70),
        ),
    ]
