# Generated by Django 2.2.13 on 2024-04-05 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0008_auto_20240405_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruitment',
            name='role',
        ),
        migrations.AddField(
            model_name='recruitment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Shortlisted', 'Shortlisted'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(default='emp671', max_length=70),
        ),
    ]
