# Generated by Django 2.2.13 on 2024-04-05 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0014_auto_20240406_0132'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Calendar',
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(default='emp721', max_length=70),
        ),
    ]
