# Generated by Django 2.2.13 on 2024-04-06 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0017_auto_20240406_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(default='emp529', max_length=70),
        ),
    ]
